#!/bin/bash
# Cleans up after the plots are made

ep="$1"
x="$2"
keep="$3"

mkdir "../output/differencePlots_ep${ep}x${x}"
mv *.pdf "../output/differencePlots_ep${ep}x${x}"

if [ "$keep" == "y" ]; then
  (
    cd "../resources/tempCase/plots" || exit
    python plotData.py
  )

  mv "../resources/tempCase" "../output/differencePlots_ep${ep}x${x}/ep${ep}x${x}"

elif [ "$keep" == "n" ]; then
  rm -r "../resources/tempCase"

fi